### ISSUE TITLE
Incorrect PIE report for ld.so and musl libc.so

### ISSUE THREAD

**Issue by ekilmer** [Wenzel/checksec.py#110]
When comparing results against [checksec.sh](https://github.com/slimm609/checksec.sh), I noticed that checksec.py reports `PIE: No` whereas checksec.sh reports `PIE: DSO` for the following Ubuntu 20.04 binaries:

* `/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2` (should already be present in any x86_64 Ubuntu 20.04 distro)
* `/lib/x86_64-linux-musl/libc.so` (installable via `apt install musl-dev`)

I believe `checksec.py` is wrong and `checksec.sh` is correct here because the above binaries are reported as shared objects by the `file` command.

I think the key feature with the above two binaries is that they do not contain an `interpreter` path, which looks to be a deciding factor in the LIEF code for whether the binary is PIE:

https://github.com/lief-project/LIEF/blob/255d09c92d09ebacb9473744550e1b90a8f4fd4e/src/ELF/Binary.cpp#L1184

I think this issue could be worked around in checksec.py by looking first to determine whether the binary is a shared object or not before checking with LIEF.

I wanted to get your opinion first before also potentially opening an issue on the LIEF repo.

**Comment by Wenzel** [comment]
Hi,

thank you for the detailed bug report.
it's a good idea to compare with `checksec.sh` and this project has been there for a long time.

[checksec.sh PIE code](https://github.com/slimm609/checksec.sh/blob/master/checksec#L397)
~~~
// pseudo code
switch (type) {
  case EXEC:
    -> No PIE
  case DYN:
    if 'DEBUG' in dynamic segment {
      -> PIE enabled
    } else {
      -> PIE DSO
    }
    case REL:
      -> PIE REL
    default:
      -> Not an ELF
}
~~~

I would like to rely as much as possible on LIEF, and avoid implementing custom logic in checksec.py.

LIEF's implementation of [`is_pie()`](https://github.com/lief-project/LIEF/blob/255d09c92d09ebacb9473744550e1b90a8f4fd4e/src/ELF/Binary.cpp#L1184) checks looks like this
~~~
// pseudo code
if PT_INTERP and ET_DYN {
  return true
} else {
  return false
}
~~~

ping @romainthomas :arrow_right: what about updating `is_pie()` check to only check the presence of `ET_DYN` ?

@ekilmer in the meantime, i could update checksec.py implemtation like this:
~~~python
    @property
    def pie(self) -> PIEType:
        if self.bin.header.file_type == E_TYPE.DYNAMIC:
            if self.bin.has(lief.ELF.DYNAMIC_TAGS.DEBUG):
                return PIEType.PIE
            else:
                return PIEType.DSO
        elif self.bin.header.file_type == E_TYPE.RELOCATABLE:
            return PIEType.REL
        return PIEType.No
~~~
:arrow_up: and this adds support for relocatable PIE type :wink:

**Comment by ekilmer** [comment]
This looks great! Thank you for the informative response!

**Comment by Wenzel** [comment]
Released a new version of checksec.py, closing this issue !
