### ISSUE TITLE
checksec.exe reports "Force Integrity" as "yes" for everything

### ISSUE THREAD

**Issue by wdormann** [Wenzel/checksec.py#70]
I don't think the "Force Integrity" check is working.  It appears to report everything as "yes" regardless of what the target has.
For testing purposes, on a Windows 10 box, an example file with Force Integrity enabled is c:\windows\system32\CameraSettingsUIHost.exe

An example file without Force Integrity enabled is c:\windows\system32\calc.exe

But checksec.exe says "yes" to both:
![Screen Shot 2020-10-03 at 4 05 56 PM](https://user-images.githubusercontent.com/14325582/95000842-5b4bf200-0592-11eb-9071-8ec8fc2cde25.png)

**Comment by Wenzel** [comment]
Hi @wdormann ,

thanks for your report.

Would it be possible to link your 2 binaries in this issue ?
I would like to like at them in detail with the `lief` library.

This is what checksec.py does:
https://github.com/Wenzel/checksec.py/blob/master/checksec/pe.py#L95

~~~Python
    @property
    def has_force_integrity(self) -> bool:
        """Whether FORCE_INTEGRITY is enabled"""
        # 2011 ?
        return self.bin.optional_header.has(DLL_CHARACTERISTICS.FORCE_INTEGRITY)
~~~

I also looked at the Rich output code and couldn't spot an issue there.
The binaries would help !

Thanks.

**Comment by Wenzel** [comment]
For the binaries, I had a win 10 VM, I got them out and can repro the bug

I'm working on it.

**Comment by Wenzel** [comment]
@wdormann 

I fixed your issue in the latest PR, and another issue, the `force_intergrity` key wasn't inserted in the JSON output: https://github.com/Wenzel/checksec.py/pull/72

I also published `v0.4.3`:
https://github.com/Wenzel/checksec.py/releases/tag/v0.4.3

Feel free to close this issue.

Thank you very much !

**Comment by Wenzel** [comment]
Confirmation:
![Capture d’écran de 2020-10-04 19-59-43](https://user-images.githubusercontent.com/964610/95023764-1ce03100-067f-11eb-8afc-4d80fe238826.png)

**Comment by wdormann** [comment]
Looks good! 
![checksec_fixed](https://user-images.githubusercontent.com/14325582/95207576-01c40d00-07b6-11eb-87c5-da05fa499c3d.png)
 Here is the latest, along with an old vlc.exe for good measure.
